### PR TITLE
[documentation] added dogshit.txt

### PR DESCRIPTION
**Pull request by B00daW**
i'm so fucking tired right now and i hate work at the moment.  github is slightly irritating but i know that if i persevere that everything will be ok; and i'm having a great time working with bazz, xyz, and yuki-chan (whatever fucking name he wants right now) on this project.  thanx. :)

### CODE REVIEW

**Comment by B00daW** [comment]
hey i word vomited!  i'm still confused!

**Comment by bazz1tv** [comment]
Please write something in your dogshit file (I'm pretending to give you valuable feedback you must enact on before I accept your PR)

**Comment by B00daW** [comment]
ok i committed those changes!

**Comment by bazz1tv** [comment]
OK that looks good! thanks. Here's some cake. 🍰

**Pull request merged**
